apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  annotations:
    azure.workload.identity/use: "true"
spec:
  containers:
  - name: example-container
    image: nginx
    env:
    - name: AZURE_CLIENT_ID
      value: 2a05e9df-357f-4659-8525-4b8f39bf7a2e
 