name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the YAML file
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up kubectl
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Authenticate to the Kubernetes cluster
      - name: Authenticate to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "${KUBECONFIG}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

      # Deploy the YAML file
      - name: Apply Kubernetes manifests
        run: kubectl apply -f deployment.yaml

      # Verify deployment
      - name: Verify Deployment Status
        run: kubectl rollout status deployment/uimicroservice




          # env:
          # - name: ENVIRONMENT
          #   value: "production"
          # - name: LOG_LEVEL
          #   value: "info"
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: uimicroservice
#   labels:
#     app: microuimicrotask
#   namespace: default
# spec:
#   replicas: 5
#   selector:
#     matchLabels:
#       app: microuimicrotask
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#   template:
#     metadata:
#       labels:
#         app: microuimicrotask
#       annotations:
#         prometheus.io/scrape: "true"
#         prometheus.io/port: "80"
#     spec:
#       serviceAccountName: uimicroservice-sa
#       priorityClassName: high-priority
#       dnsConfig:
#         nameservers:
#           - 8.8.8.8
#           - 8.8.4.4
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#               - matchExpressions:
#                   - key: kubernetes.io/hostname
#                     operator: In
#                     values:
#                       - aks-agentpool-34244086-vmss000000
#                       - aks-userpool-23695494-vmss000000
#         podAntiAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             - labelSelector:
#                 matchExpressions:
#                   - key: app
#                     operator: In
#                     values:
#                       - microuimicrotask
#               topologyKey: "kubernetes.io/hostname"
#       containers:
#         - name: uimicroservice
#           image: nginx
#           ports:
#             - containerPort: 80
#           resources:
#             requests:
#               memory: "512Mi"
#               cpu: "500m"
#             limits:
#               memory: "1Gi"
#               cpu: "1000m"
#           livenessProbe:
#             httpGet:
#               path: /healthz
#               port: 80
#             initialDelaySeconds: 5
#             periodSeconds: 10
#           readinessProbe:
#             httpGet:
#               path: /readiness
#               port: 80
#             initialDelaySeconds: 5
#             periodSeconds: 10
#           env:
#             - name: ENVIRONMENT
#               value: "production"
#             - name: LOG_LEVEL
#               value: "info"




                       




